
# Resume Audit Study

# Create functions for data input

library(tidyverse)

# Function for Data Input at Resume Level ####

# Create data frame
dat_res <- data.frame(
  res_id = integer(),
  post_id = character(),
  sub_order = integer(),
  res_type = character(),
  pcat = character(),
  pcity = character(),
  ptitle = character(),
  fname = character(),
  rname = character(),
  subday = character(),
  subtime = character(),
  rsp = character(),
  rsp_day = character(),
  rsp_time = character(),
  rsp_cat = character(),
  rsp_msg = character(),
  rsp_call = character(),
  rsp_wechat = character(),
  cmt = character()
)

radd <- function(
  res_id,
  post_id,
  sub_order,
  res_type,
  pcat,
  pcity,
  ptitle,
  fname,
  rname,
  subday,
  subtime,
  rsp,
  rsp_day,
  rsp_time,
  rsp_cat,
  rsp_msg,
  rsp_call,
  rsp_wechat,
  cmt
) {
  new_row  <- data.frame(
    res_id = res_id,
    post_id = as.character(post_id),
    sub_order = sub_order,
    res_type = res_type,
    pcat = pcat,
    pcity = pcity,
    ptitle = ptitle,
    fname = fname,
    rname = rname,
    subday = subday,
    subtime = subtime,
    rsp = rsp,
    rsp_day = rsp_day,
    rsp_time = rsp_time,
    rsp_cat = rsp_cat,
    rsp_msg = rsp_msg,
    rsp_call = rsp_call,
    rsp_wechat = rsp_wechat,
    cmt = cmt
  )
  dat <- bind_rows(dat_res, new_row)
  return(dat)
}

# Function for Data Input at Post Level ####

# Create data frame
dat_post <- data.frame(
  post_id = character(),
  preg = character(),
  pcat = character(),
  pcity = character(),
  ptitle = character(),
  padd = character(),
  pexp = character(),
  pedu = character(),
  psal_lower = numeric(),
  psal_upper = numeric(),
  psal_mon = numeric(),
  pdeskw = character(),
  pdestxt = character(),
  pcandno = integer(),
  fname = character(),
  flogo = character(),
  findu = character(),
  fsize = character(),
  ffinc = character(),
  fpostno = integer(),
  fhrno = integer(),
  fdeskw = character(),
  fregname = character(),
  fdate_start = character(),
  fdate_end = character(),
  fcat = character(),
  fcap = character(),
  fadd = character(),
  fsco = character(),
  fdestxt = character(),
  fhour = character(),
  fdayoff = character(),
  fben = character(),
  falbum = character(),
  fhckw = character(),
  rname = character(),
  rmale = character(),
  radd = character(),
  rpos = character(),
  rsta = character(),
  rpostno = integer()
)

padd <- function(
  post_id,
  preg,
  pcat,
  pcity,
  ptitle,
  padd,
  pexp,
  pedu,
  psal_lower = NA,
  psal_upper = NA,
  psal_mon = NA,
  pdeskw,
  pdestxt,
  pcandno = NA,
  fname,
  flogo,
  findu,
  fsize,
  ffinc,
  fpostno = NA,
  fhrno = NA,
  fdeskw,
  fregname,
  fdate_start,
  fdate_end,
  fcat,
  fcap,
  fadd,
  fsco,
  fdestxt,
  fhour,
  fdayoff,
  fben,
  falbum,
  fhckw,
  rname,
  rmale,
  radd,
  rpos,
  rsta,
  rpostno = NA
) {
  new_row <- data.frame(
    post_id = as.character(post_id),
    preg = preg,
    pcat = pcat,
    pcity = pcity,
    ptitle = ptitle,
    padd = padd,
    pexp = pexp,
    pedu = pedu,
    psal_lower = psal_lower,
    psal_upper = psal_upper,
    psal_mon = psal_mon,
    pdeskw = pdeskw,
    pdestxt = pdestxt,
    pcandno = pcandno,
    fname = fname,
    flogo = flogo,
    findu = findu,
    fsize = fsize,
    ffinc = ffinc,
    fpostno = fpostno,
    fhrno = fhrno,
    fdeskw = fdeskw,
    fregname = fregname,
    fdate_start = fdate_start,
    fdate_end = fdate_end,
    fcat = fcat,
    fcap = fcap,
    fadd = fadd,
    fsco = fsco,
    fdestxt = fdestxt,
    fhour = fhour,
    fdayoff = fdayoff,
    fben = fben,
    falbum = falbum,
    fhckw = fhckw,
    rname = rname,
    rmale = rmale,
    radd = radd,
    rpos = rpos,
    rsta = rsta,
    rpostno = rpostno
  )
  dat <- bind_rows(dat_post, new_row)
  return(dat)
}
